[package]
name = "polycentrics-frontend"
description = "Web-frontend for Polycentrics using Yew."
readme = "../README.md"
version = "0.3.0"
license = "GPL-3.0-only"
authors = ["m4dh0rs3 <schoeps.benedikt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
