# Config for the WASM bundler [Trunk](https://github.com/thedodd/trunk)

[build]
# the index HTML file to drive the bundling process
target = "frontend/index.html"
# build in release mode
release = false
# the output dir for all final assets
dist = "frontend/public"
# the public URL from which assets are to be served
public_url = "/"

[watch]
# paths to watch, defaults to build target parent folder
# TODO: move into workspace directory when [#181](https://github.com/thedodd/trunk/issues/181) is closed
path = ["backend/src", "frontend"]

[serve]
# the port to serve on
port = 8080
# open a browser tab once the initial build is complete
open = true

[clean]
# the output dir for all final assets
dist = "frontend/public"